Traceback (most recent call last):
  File "C:\Users\Miguel\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Miguel\anaconda3\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miguel\anaconda3\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miguel\anaconda3\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miguel\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Miguel\anaconda3\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Miguel\anaconda3\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Miguel\anaconda3\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data_cali_hp = fetch_california_housing(as_frame=True)
print(data_cali_hp.DESCR) #<- uncomment to read a brief data description
data_cali_hp = data_cali_hp.frame
#data_cali_hp.info()
#data_cali_hp.head()

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m data_cali_hp [38;5;241m=[39m fetch_california_housing(as_frame[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m      2[0m [38;5;28mprint[39m(data_cali_hp[38;5;241m.[39mDESCR) [38;5;66;03m#<- uncomment to read a brief data description[39;00m
[0;32m      3[0m data_cali_hp [38;5;241m=[39m data_cali_hp[38;5;241m.[39mframe

File [1;32m~\anaconda3\Lib\site-packages\sklearn\datasets\_california_housing.py:153[0m, in [0;36mfetch_california_housing[1;34m(data_home, download_if_missing, return_X_y, as_frame)[0m
[0;32m    150[0m     remove(archive_path)
[0;32m    152[0m [38;5;28;01melse[39;00m:
[1;32m--> 153[0m     cal_housing [38;5;241m=[39m joblib[38;5;241m.[39mload(filepath)
[0;32m    155[0m feature_names [38;5;241m=[39m [
[0;32m    156[0m     [38;5;124m"[39m[38;5;124mMedInc[39m[38;5;124m"[39m,
[0;32m    157[0m     [38;5;124m"[39m[38;5;124mHouseAge[39m[38;5;124m"[39m,
[1;32m   (...)[0m
[0;32m    163[0m     [38;5;124m"[39m[38;5;124mLongitude[39m[38;5;124m"[39m,
[0;32m    164[0m ]
[0;32m    166[0m target, data [38;5;241m=[39m cal_housing[:, [38;5;241m0[39m], cal_housing[:, [38;5;241m1[39m:]

File [1;32m~\anaconda3\Lib\site-packages\joblib\numpy_pickle.py:587[0m, in [0;36mload[1;34m(filename, mmap_mode)[0m
[0;32m    581[0m             [38;5;28;01mif[39;00m [38;5;28misinstance[39m(fobj, [38;5;28mstr[39m):
[0;32m    582[0m                 [38;5;66;03m# if the returned file object is a string, this means we[39;00m
[0;32m    583[0m                 [38;5;66;03m# try to load a pickle file generated with an version of[39;00m
[0;32m    584[0m                 [38;5;66;03m# Joblib so we load it with joblib compatibility function.[39;00m
[0;32m    585[0m                 [38;5;28;01mreturn[39;00m load_compatibility(fobj)
[1;32m--> 587[0m             obj [38;5;241m=[39m _unpickle(fobj, filename, mmap_mode)
[0;32m    588[0m [38;5;28;01mreturn[39;00m obj

File [1;32m~\anaconda3\Lib\site-packages\joblib\numpy_pickle.py:506[0m, in [0;36m_unpickle[1;34m(fobj, filename, mmap_mode)[0m
[0;32m    504[0m obj [38;5;241m=[39m [38;5;28;01mNone[39;00m
[0;32m    505[0m [38;5;28;01mtry[39;00m:
[1;32m--> 506[0m     obj [38;5;241m=[39m unpickler[38;5;241m.[39mload()
[0;32m    507[0m     [38;5;28;01mif[39;00m unpickler[38;5;241m.[39mcompat_mode:
[0;32m    508[0m         warnings[38;5;241m.[39mwarn([38;5;124m"[39m[38;5;124mThe file [39m[38;5;124m'[39m[38;5;132;01m%s[39;00m[38;5;124m'[39m[38;5;124m has been generated with a [39m[38;5;124m"[39m
[0;32m    509[0m                       [38;5;124m"[39m[38;5;124mjoblib version less than 0.10. [39m[38;5;124m"[39m
[0;32m    510[0m                       [38;5;124m"[39m[38;5;124mPlease regenerate this pickle file.[39m[38;5;124m"[39m
[0;32m    511[0m                       [38;5;241m%[39m filename,
[0;32m    512[0m                       [38;5;167;01mDeprecationWarning[39;00m, stacklevel[38;5;241m=[39m[38;5;241m3[39m)

File [1;32m~\anaconda3\Lib\pickle.py:1213[0m, in [0;36m_Unpickler.load[1;34m(self)[0m
[0;32m   1211[0m             [38;5;28;01mraise[39;00m [38;5;167;01mEOFError[39;00m
[0;32m   1212[0m         [38;5;28;01massert[39;00m [38;5;28misinstance[39m(key, bytes_types)
[1;32m-> 1213[0m         dispatch[key[[38;5;241m0[39m]]([38;5;28mself[39m)
[0;32m   1214[0m [38;5;28;01mexcept[39;00m _Stop [38;5;28;01mas[39;00m stopinst:
[0;32m   1215[0m     [38;5;28;01mreturn[39;00m stopinst[38;5;241m.[39mvalue

[1;31mKeyError[0m: 194
KeyError: 194

